// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jcbutiqcahcxrkhjwtub.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpjYnV0aXFjYWhjeHJraGp3dHViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyNDAwNDEsImV4cCI6MjA3MjgxNjA0MX0._h51EG0KL4PWbT7Ur3-03m5W3d1T8yIyYjB6zJbRk-0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});